-- 01_DDL_Tables.sql w SQL Server

CREATE TABLE CAR_CATEGORIES (
    CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL,
    DESCRIPTION NVARCHAR(255)
);

CREATE TABLE BRANCHES (
    BRANCH_ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    ADDRESS NVARCHAR(255) NOT NULL,
    CITY NVARCHAR(100) NOT NULL,
    POSTAL_CODE NVARCHAR(10),
    PHONE NVARCHAR(20),
    EMAIL NVARCHAR(100),
    IS_ACTIVE INT DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1))
);

CREATE TABLE CARS (
    CAR_ID INT IDENTITY(1,1) PRIMARY KEY,
    BRAND NVARCHAR(50) NOT NULL,
    MODEL NVARCHAR(50) NOT NULL,
    YEAR INT NOT NULL,
    PLATE_NUMBER NVARCHAR(20) NOT NULL UNIQUE,
    VIN NVARCHAR(17) NOT NULL UNIQUE,
    DAILY_RATE DECIMAL(10,2) NOT NULL CHECK (DAILY_RATE > 0),
    CATEGORY_ID INT NOT NULL,
    BRANCH_ID INT NOT NULL,
    COLOR NVARCHAR(30),
    SEATS INT DEFAULT 5,
    MILEAGE INT DEFAULT 0 CHECK (MILEAGE >= 0),
    STATUS NVARCHAR(20) DEFAULT 'AVAILABLE' CHECK (STATUS IN ('AVAILABLE', 'RENTED', 'IN_SERVICE', 'UNAVAILABLE')),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CAR_CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID)
);

CREATE TABLE CLIENTS (
    CLIENT_ID INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME NVARCHAR(50) NOT NULL,
    LAST_NAME NVARCHAR(50) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL UNIQUE,
    PHONE NVARCHAR(20),
    PESEL NVARCHAR(11) UNIQUE,
    ADDRESS NVARCHAR(255),
    CITY NVARCHAR(100),
    POSTAL_CODE NVARCHAR(10),
    REGISTRATION_DATE DATETIME DEFAULT GETDATE(),
    PASSWORD_HASH NVARCHAR(255) NOT NULL,
    IS_BLOCKED INT DEFAULT 0 CHECK (IS_BLOCKED IN (0, 1)),
    PENALTY_MULTIPLIER DECIMAL(3,2) DEFAULT 1.00
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME NVARCHAR(50) NOT NULL,
    LAST_NAME NVARCHAR(50) NOT NULL,
    EMAIL NVARCHAR(100) NOT NULL UNIQUE,
    PHONE NVARCHAR(20),
    POSITION NVARCHAR(50) NOT NULL,
    BRANCH_ID INT NOT NULL,
    HIRE_DATE DATETIME DEFAULT GETDATE(),
    PASSWORD_HASH NVARCHAR(255) NOT NULL,
    IS_ACTIVE INT DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID)
);

CREATE TABLE RENTALS (
    RENTAL_ID INT IDENTITY(1,1) PRIMARY KEY,
    CLIENT_ID INT NOT NULL,
    CAR_ID INT NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    ACTUAL_RETURN_DATE DATETIME,
    STATUS NVARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'COMPLETED', 'CANCELLED', 'EXTENDED')),
    TOTAL_PRICE DECIMAL(10,2),
    START_MILEAGE INT NOT NULL,
    END_MILEAGE INT,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID)
);

CREATE TABLE PAYMENT_STATUSES (
    STATUS_ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL
);

CREATE TABLE PAYMENTS (
    PAYMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
    RENTAL_ID INT NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL CHECK (AMOUNT > 0),
    PAYMENT_DATE DATETIME,
    STATUS_ID INT NOT NULL,
    INSTALLMENT_NO INT DEFAULT 1,
    TOTAL_INSTALLMENTS INT DEFAULT 1,
    PAYMENT_METHOD NVARCHAR(50),
    FOREIGN KEY (RENTAL_ID) REFERENCES RENTALS(RENTAL_ID),
    FOREIGN KEY (STATUS_ID) REFERENCES PAYMENT_STATUSES(STATUS_ID)
);

CREATE TABLE PENALTIES (
    PENALTY_ID INT IDENTITY(1,1) PRIMARY KEY,
    CLIENT_ID INT NOT NULL,
    RENTAL_ID INT,
    REASON NVARCHAR(255) NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL CHECK (AMOUNT >= 0),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    FOREIGN KEY (RENTAL_ID) REFERENCES RENTALS(RENTAL_ID)
);

CREATE TABLE RESERVATION_STATUSES (
    STATUS_ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL
);

CREATE TABLE RESERVATIONS (
    RESERVATION_ID INT IDENTITY(1,1) PRIMARY KEY,
    CLIENT_ID INT NOT NULL,
    CAR_ID INT NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    STATUS_ID INT NOT NULL,
    CREATED_AT DATETIME DEFAULT GETDATE(),
    NOTES NVARCHAR(MAX),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID),
    FOREIGN KEY (STATUS_ID) REFERENCES RESERVATION_STATUSES(STATUS_ID)
);

CREATE TABLE SERVICE_STATUSES (
    STATUS_ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL
);

CREATE TABLE SERVICES (
    SERVICE_ID INT IDENTITY(1,1) PRIMARY KEY,
    CAR_ID INT NOT NULL,
    DESCRIPTION NVARCHAR(MAX) NOT NULL,
    COST DECIMAL(10,2),
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME,
    STATUS_ID INT NOT NULL,
    NOTES NVARCHAR(MAX),
    FOREIGN KEY (CAR_ID) REFERENCES CARS(CAR_ID),
    FOREIGN KEY (STATUS_ID) REFERENCES SERVICE_STATUSES(STATUS_ID)
);

CREATE TABLE CHANGE_HISTORY (
    HISTORY_ID INT IDENTITY(1,1) PRIMARY KEY,
    TABLE_NAME NVARCHAR(50) NOT NULL,
    RECORD_ID INT NOT NULL,
    OLD_VALUES NVARCHAR(MAX),
    NEW_VALUES NVARCHAR(MAX),
    CHANGE_DATE DATETIME2 DEFAULT GETDATE(),
    CHANGED_BY NVARCHAR(100),
    OPERATION_TYPE NVARCHAR(20) NOT NULL CHECK (OPERATION_TYPE IN ('INSERT', 'UPDATE', 'DELETE'))
);
