-- ============================================
-- CarRent DB - Tworzenie tabel
-- Systemy Baz Danych
-- Adam Przestrzelski, Paweł Sławiński
-- ============================================

-- ==========================================
-- ENCJE SŁOWNIKOWE
-- ==========================================

CREATE TABLE CAR_CATEGORIES (
    CATEGORY_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME          VARCHAR2(50)  NOT NULL UNIQUE,
    DESCRIPTION   VARCHAR2(200)
);

CREATE TABLE RESERVATION_STATUSES (
    STATUS_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE PAYMENT_STATUSES (
    STATUS_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE SERVICE_STATUSES (
    STATUS_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(50) NOT NULL UNIQUE
);

-- ==========================================
-- ENCJE GŁÓWNE
-- ==========================================

-- Oddziały
CREATE TABLE BRANCHES (
    BRANCH_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(100) NOT NULL,
    ADDRESS     VARCHAR2(200) NOT NULL,
    CITY        VARCHAR2(100) NOT NULL,
    POSTAL_CODE VARCHAR2(10),
    PHONE       VARCHAR2(20),
    EMAIL       VARCHAR2(100),
    IS_ACTIVE   NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1))
);

-- Pracownicy
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME    VARCHAR2(50)  NOT NULL,
    LAST_NAME     VARCHAR2(50)  NOT NULL,
    EMAIL         VARCHAR2(100) NOT NULL UNIQUE,
    PHONE         VARCHAR2(20),
    POSITION      VARCHAR2(50)  NOT NULL,
    BRANCH_ID     NUMBER        NOT NULL,
    HIRE_DATE     DATE          DEFAULT SYSDATE NOT NULL,
    PASSWORD_HASH VARCHAR2(256) NOT NULL,
    IS_ACTIVE     NUMBER(1)     DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT FK_EMPLOYEE_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID)
);

-- Klienci
CREATE TABLE CLIENTS (
    CLIENT_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME         VARCHAR2(50)  NOT NULL,
    LAST_NAME          VARCHAR2(50)  NOT NULL,
    EMAIL              VARCHAR2(100) NOT NULL UNIQUE,
    PHONE              VARCHAR2(20),
    PESEL              VARCHAR2(11)  UNIQUE,
    ADDRESS            VARCHAR2(200),
    CITY               VARCHAR2(100),
    POSTAL_CODE        VARCHAR2(10),
    IS_BLOCKED         NUMBER(1)     DEFAULT 0 NOT NULL CHECK (IS_BLOCKED IN (0, 1)),
    PENALTY_MULTIPLIER NUMBER(3,2)   DEFAULT 1.00 NOT NULL,
    PASSWORD_HASH      VARCHAR2(256) NOT NULL,
    CREATED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- Samochody
CREATE TABLE CARS (
    CAR_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BRAND         VARCHAR2(50)  NOT NULL,
    MODEL         VARCHAR2(50)  NOT NULL,
    YEAR          NUMBER(4)     NOT NULL,
    PLATE_NUMBER  VARCHAR2(15)  NOT NULL UNIQUE,
    VIN           VARCHAR2(17)  NOT NULL UNIQUE,
    DAILY_RATE    NUMBER(10,2)  NOT NULL CHECK (DAILY_RATE > 0),
    CATEGORY_ID   NUMBER        NOT NULL,
    BRANCH_ID     NUMBER        NOT NULL,
    STATUS        VARCHAR2(20)  DEFAULT 'AVAILABLE' NOT NULL
                  CHECK (STATUS IN ('AVAILABLE', 'RENTED', 'IN_SERVICE', 'UNAVAILABLE')),
    MILEAGE       NUMBER(10)    DEFAULT 0 NOT NULL,
    COLOR         VARCHAR2(30),
    SEATS         NUMBER(2)     DEFAULT 5,
    CONSTRAINT FK_CAR_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CAR_CATEGORIES(CATEGORY_ID),
    CONSTRAINT FK_CAR_BRANCH   FOREIGN KEY (BRANCH_ID)   REFERENCES BRANCHES(BRANCH_ID)
);

-- Rezerwacje
CREATE TABLE RESERVATIONS (
    RESERVATION_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID       NUMBER    NOT NULL,
    CAR_ID          NUMBER    NOT NULL,
    START_DATE      DATE      NOT NULL,
    END_DATE        DATE      NOT NULL,
    STATUS_ID       NUMBER    NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    NOTES           VARCHAR2(500),
    CONSTRAINT FK_RES_CLIENT   FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    CONSTRAINT FK_RES_CAR      FOREIGN KEY (CAR_ID)    REFERENCES CARS(CAR_ID),
    CONSTRAINT FK_RES_STATUS   FOREIGN KEY (STATUS_ID) REFERENCES RESERVATION_STATUSES(STATUS_ID),
    CONSTRAINT CHK_RES_DATES   CHECK (END_DATE > START_DATE)
);

-- Wypożyczenia
CREATE TABLE RENTALS (
    RENTAL_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESERVATION_ID  NUMBER,
    CLIENT_ID       NUMBER        NOT NULL,
    CAR_ID          NUMBER        NOT NULL,
    START_DATE      DATE          NOT NULL,
    END_DATE        DATE          NOT NULL,
    ACTUAL_END_DATE DATE,
    TOTAL_PRICE     NUMBER(10,2)  NOT NULL CHECK (TOTAL_PRICE >= 0),
    STATUS          VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL
                    CHECK (STATUS IN ('ACTIVE', 'COMPLETED', 'CANCELLED')),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_RENTAL_RES    FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATIONS(RESERVATION_ID),
    CONSTRAINT FK_RENTAL_CLIENT FOREIGN KEY (CLIENT_ID)      REFERENCES CLIENTS(CLIENT_ID),
    CONSTRAINT FK_RENTAL_CAR    FOREIGN KEY (CAR_ID)         REFERENCES CARS(CAR_ID),
    CONSTRAINT CHK_RENTAL_DATES CHECK (END_DATE >= START_DATE)
);

-- Płatności
CREATE TABLE PAYMENTS (
    PAYMENT_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RENTAL_ID          NUMBER       NOT NULL,
    AMOUNT             NUMBER(10,2) NOT NULL CHECK (AMOUNT > 0),
    PAYMENT_DATE       DATE         DEFAULT SYSDATE,
    STATUS_ID          NUMBER       NOT NULL,
    INSTALLMENT_NO     NUMBER(3)    DEFAULT 1 NOT NULL,
    TOTAL_INSTALLMENTS NUMBER(3)    DEFAULT 1 NOT NULL,
    PAYMENT_METHOD     VARCHAR2(30),
    CONSTRAINT FK_PAY_RENTAL FOREIGN KEY (RENTAL_ID) REFERENCES RENTALS(RENTAL_ID),
    CONSTRAINT FK_PAY_STATUS FOREIGN KEY (STATUS_ID) REFERENCES PAYMENT_STATUSES(STATUS_ID)
);

-- Kary
CREATE TABLE PENALTIES (
    PENALTY_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID    NUMBER        NOT NULL,
    RENTAL_ID    NUMBER,
    REASON       VARCHAR2(500) NOT NULL,
    AMOUNT       NUMBER(10,2)  NOT NULL CHECK (AMOUNT >= 0),
    CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PEN_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    CONSTRAINT FK_PEN_RENTAL FOREIGN KEY (RENTAL_ID) REFERENCES RENTALS(RENTAL_ID)
);

-- Serwis
CREATE TABLE SERVICES (
    SERVICE_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CAR_ID        NUMBER        NOT NULL,
    DESCRIPTION   VARCHAR2(500) NOT NULL,
    COST          NUMBER(10,2)  DEFAULT 0 NOT NULL,
    STATUS_ID     NUMBER        NOT NULL,
    START_DATE    DATE          NOT NULL,
    END_DATE      DATE,
    NOTES         VARCHAR2(500),
    CONSTRAINT FK_SRV_CAR    FOREIGN KEY (CAR_ID)    REFERENCES CARS(CAR_ID),
    CONSTRAINT FK_SRV_STATUS FOREIGN KEY (STATUS_ID) REFERENCES SERVICE_STATUSES(STATUS_ID)
);

-- Historia zmian
CREATE TABLE CHANGE_HISTORY (
    HISTORY_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TABLE_NAME      VARCHAR2(50)  NOT NULL,
    RECORD_ID       NUMBER        NOT NULL,
    OLD_VALUES      CLOB,
    NEW_VALUES      CLOB,
    CHANGE_DATE     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CHANGED_BY      VARCHAR2(100) DEFAULT USER NOT NULL,
    OPERATION_TYPE  VARCHAR2(10)  NOT NULL CHECK (OPERATION_TYPE IN ('INSERT', 'UPDATE', 'DELETE'))
);
