-- ============================================
-- CarRent DB - Indeksy
-- ============================================

-- Wypożyczenia (najczęściej odpytywana tabela)
CREATE INDEX IDX_RENTAL_CLIENT     ON RENTALS(CLIENT_ID);
CREATE INDEX IDX_RENTAL_CAR        ON RENTALS(CAR_ID);
CREATE INDEX IDX_RENTAL_START_DATE ON RENTALS(START_DATE);
CREATE INDEX IDX_RENTAL_END_DATE   ON RENTALS(END_DATE);
CREATE INDEX IDX_RENTAL_STATUS     ON RENTALS(STATUS);

-- Rezerwacje
CREATE INDEX IDX_RES_CLIENT    ON RESERVATIONS(CLIENT_ID);
CREATE INDEX IDX_RES_CAR       ON RESERVATIONS(CAR_ID);
CREATE INDEX IDX_RES_STATUS    ON RESERVATIONS(STATUS_ID);
CREATE INDEX IDX_RES_CREATED   ON RESERVATIONS(CREATED_AT);

-- Samochody
CREATE INDEX IDX_CAR_CATEGORY  ON CARS(CATEGORY_ID);
CREATE INDEX IDX_CAR_STATUS    ON CARS(STATUS);
CREATE INDEX IDX_CAR_BRANCH    ON CARS(BRANCH_ID);

-- Płatności
CREATE INDEX IDX_PAY_RENTAL    ON PAYMENTS(RENTAL_ID);
CREATE INDEX IDX_PAY_STATUS    ON PAYMENTS(STATUS_ID);
CREATE INDEX IDX_PAY_DATE      ON PAYMENTS(PAYMENT_DATE);

-- Kary
CREATE INDEX IDX_PEN_CLIENT    ON PENALTIES(CLIENT_ID);
CREATE INDEX IDX_PEN_RENTAL    ON PENALTIES(RENTAL_ID);

-- Historia zmian
CREATE INDEX IDX_HIST_TABLE    ON CHANGE_HISTORY(TABLE_NAME);
CREATE INDEX IDX_HIST_RECORD   ON CHANGE_HISTORY(RECORD_ID);
CREATE INDEX IDX_HIST_DATE     ON CHANGE_HISTORY(CHANGE_DATE);

-- Pracownicy
CREATE INDEX IDX_EMP_BRANCH    ON EMPLOYEES(BRANCH_ID);

-- Serwis
CREATE INDEX IDX_SRV_CAR       ON SERVICES(CAR_ID);
CREATE INDEX IDX_SRV_STATUS    ON SERVICES(STATUS_ID);
