-- 02_DDL_Indexes.sql w SQL Server

CREATE INDEX IDX_CARS_CATEGORY ON CARS(CATEGORY_ID);
CREATE INDEX IDX_CARS_BRANCH ON CARS(BRANCH_ID);
CREATE INDEX IDX_CARS_STATUS ON CARS(STATUS);

CREATE INDEX IDX_CLIENTS_EMAIL ON CLIENTS(EMAIL);
CREATE INDEX IDX_CLIENTS_PESEL ON CLIENTS(PESEL);

CREATE INDEX IDX_RENTALS_CLIENT ON RENTALS(CLIENT_ID);
CREATE INDEX IDX_RENTALS_CAR ON RENTALS(CAR_ID);
CREATE INDEX IDX_RENTALS_DATES ON RENTALS(START_DATE, END_DATE);
CREATE INDEX IDX_RENTALS_STATUS ON RENTALS(STATUS);

CREATE INDEX IDX_PAYMENTS_RENTAL ON PAYMENTS(RENTAL_ID);
CREATE INDEX IDX_PAYMENTS_STATUS ON PAYMENTS(STATUS_ID);

CREATE INDEX IDX_PENALTIES_CLIENT ON PENALTIES(CLIENT_ID);
CREATE INDEX IDX_PENALTIES_RENTAL ON PENALTIES(RENTAL_ID);

CREATE INDEX IDX_RESERVATIONS_CLIENT ON RESERVATIONS(CLIENT_ID);
CREATE INDEX IDX_RESERVATIONS_CAR ON RESERVATIONS(CAR_ID);
CREATE INDEX IDX_RESERVATIONS_STATUS ON RESERVATIONS(STATUS_ID);
CREATE INDEX IDX_RESERVATIONS_DATES ON RESERVATIONS(START_DATE, END_DATE);

CREATE INDEX IDX_SERVICES_CAR ON SERVICES(CAR_ID);
CREATE INDEX IDX_SERVICES_STATUS ON SERVICES(STATUS_ID);

CREATE INDEX IDX_HISTORY_TABLE ON CHANGE_HISTORY(TABLE_NAME, RECORD_ID);
CREATE INDEX IDX_HISTORY_DATE ON CHANGE_HISTORY(CHANGE_DATE);
