-- ============================================
-- CarRent DB - Widoki
-- ============================================

-- V_AVAILABLE_CARS - lista dostępnych samochodów z kategorią i oddziałem
CREATE OR REPLACE VIEW V_AVAILABLE_CARS AS
SELECT
    c.CAR_ID,
    c.BRAND,
    c.MODEL,
    c.YEAR,
    c.PLATE_NUMBER,
    c.DAILY_RATE,
    c.COLOR,
    c.SEATS,
    c.MILEAGE,
    cat.NAME       AS CATEGORY_NAME,
    b.NAME         AS BRANCH_NAME,
    b.CITY         AS BRANCH_CITY
FROM CARS c
JOIN CAR_CATEGORIES cat ON c.CATEGORY_ID = cat.CATEGORY_ID
JOIN BRANCHES b         ON c.BRANCH_ID   = b.BRANCH_ID
WHERE c.STATUS = 'AVAILABLE';

-- V_CLIENT_RENTALS - historia wypożyczeń klienta
CREATE OR REPLACE VIEW V_CLIENT_RENTALS AS
SELECT
    r.RENTAL_ID,
    cl.CLIENT_ID,
    cl.FIRST_NAME || ' ' || cl.LAST_NAME AS CLIENT_NAME,
    cl.EMAIL        AS CLIENT_EMAIL,
    c.BRAND || ' ' || c.MODEL            AS CAR_NAME,
    c.PLATE_NUMBER,
    r.START_DATE,
    r.END_DATE,
    r.ACTUAL_END_DATE,
    r.TOTAL_PRICE,
    r.STATUS        AS RENTAL_STATUS,
    r.CREATED_AT
FROM RENTALS r
JOIN CLIENTS cl ON r.CLIENT_ID = cl.CLIENT_ID
JOIN CARS c     ON r.CAR_ID    = c.CAR_ID
ORDER BY r.CREATED_AT DESC;

-- V_MONTHLY_REVENUE - raport przychodów miesięcznych
CREATE OR REPLACE VIEW V_MONTHLY_REVENUE AS
SELECT
    EXTRACT(YEAR FROM p.PAYMENT_DATE)  AS REVENUE_YEAR,
    EXTRACT(MONTH FROM p.PAYMENT_DATE) AS REVENUE_MONTH,
    COUNT(DISTINCT r.RENTAL_ID)        AS TOTAL_RENTALS,
    COUNT(p.PAYMENT_ID)                AS TOTAL_PAYMENTS,
    SUM(p.AMOUNT)                      AS TOTAL_REVENUE,
    ROUND(AVG(p.AMOUNT), 2)            AS AVG_PAYMENT
FROM PAYMENTS p
JOIN RENTALS r  ON p.RENTAL_ID = r.RENTAL_ID
JOIN PAYMENT_STATUSES ps ON p.STATUS_ID = ps.STATUS_ID
WHERE ps.NAME = 'PAID'
GROUP BY
    EXTRACT(YEAR FROM p.PAYMENT_DATE),
    EXTRACT(MONTH FROM p.PAYMENT_DATE)
ORDER BY REVENUE_YEAR DESC, REVENUE_MONTH DESC;

-- V_CAR_UTILIZATION - wykorzystanie floty (% dni wypożyczenia)
CREATE OR REPLACE VIEW V_CAR_UTILIZATION AS
SELECT
    c.CAR_ID,
    c.BRAND || ' ' || c.MODEL AS CAR_NAME,
    c.PLATE_NUMBER,
    cat.NAME                   AS CATEGORY_NAME,
    b.NAME                     AS BRANCH_NAME,
    c.STATUS                   AS CURRENT_STATUS,
    COUNT(r.RENTAL_ID)         AS TOTAL_RENTALS,
    NVL(SUM(
        CASE
            WHEN r.ACTUAL_END_DATE IS NOT NULL
                THEN r.ACTUAL_END_DATE - r.START_DATE
            WHEN r.STATUS = 'ACTIVE'
                THEN SYSDATE - r.START_DATE
            ELSE r.END_DATE - r.START_DATE
        END
    ), 0)                      AS TOTAL_RENTAL_DAYS,
    NVL(SUM(r.TOTAL_PRICE), 0) AS TOTAL_REVENUE
FROM CARS c
LEFT JOIN RENTALS r         ON c.CAR_ID      = r.CAR_ID
JOIN CAR_CATEGORIES cat     ON c.CATEGORY_ID = cat.CATEGORY_ID
JOIN BRANCHES b             ON c.BRANCH_ID   = b.BRANCH_ID
GROUP BY
    c.CAR_ID, c.BRAND, c.MODEL, c.PLATE_NUMBER,
    cat.NAME, b.NAME, c.STATUS;

-- V_HIGH_RISK_CLIENTS - klienci wysokiego ryzyka (dużo kar)
CREATE OR REPLACE VIEW V_HIGH_RISK_CLIENTS AS
SELECT
    cl.CLIENT_ID,
    cl.FIRST_NAME || ' ' || cl.LAST_NAME AS CLIENT_NAME,
    cl.EMAIL,
    cl.IS_BLOCKED,
    cl.PENALTY_MULTIPLIER,
    COUNT(p.PENALTY_ID)        AS PENALTY_COUNT,
    NVL(SUM(p.AMOUNT), 0)     AS TOTAL_PENALTY_AMOUNT
FROM CLIENTS cl
LEFT JOIN PENALTIES p ON cl.CLIENT_ID = p.CLIENT_ID
GROUP BY
    cl.CLIENT_ID, cl.FIRST_NAME, cl.LAST_NAME,
    cl.EMAIL, cl.IS_BLOCKED, cl.PENALTY_MULTIPLIER
HAVING COUNT(p.PENALTY_ID) >= 3
ORDER BY PENALTY_COUNT DESC;
