-- 03_Views.sql w SQL Server

GO
CREATE OR ALTER VIEW V_AVAILABLE_CARS AS
SELECT 
    c.CAR_ID,
    c.BRAND,
    c.MODEL,
    c.YEAR,
    c.PLATE_NUMBER,
    c.DAILY_RATE,
    c.COLOR,
    c.SEATS,
    c.MILEAGE,
    cat.NAME AS CATEGORY_NAME,
    b.NAME AS BRANCH_NAME,
    b.CITY AS BRANCH_CITY
FROM CARS c
JOIN CAR_CATEGORIES cat ON c.CATEGORY_ID = cat.CATEGORY_ID
JOIN BRANCHES b ON c.BRANCH_ID = b.BRANCH_ID
WHERE c.STATUS = 'AVAILABLE';
GO

CREATE OR ALTER VIEW V_CLIENT_RENTALS AS
SELECT 
    r.RENTAL_ID,
    c.CLIENT_ID,
    c.FIRST_NAME + ' ' + c.LAST_NAME AS CLIENT_NAME,
    car.BRAND + ' ' + car.MODEL AS CAR_NAME,
    r.START_DATE,
    r.END_DATE,
    r.STATUS AS RENTAL_STATUS,
    r.TOTAL_PRICE,
    ISNULL((SELECT SUM(AMOUNT) FROM PAYMENTS p JOIN PAYMENT_STATUSES ps ON p.STATUS_ID = ps.STATUS_ID WHERE p.RENTAL_ID = r.RENTAL_ID AND ps.NAME = 'PAID'), 0) AS PAID_AMOUNT,
    ISNULL((SELECT SUM(AMOUNT) FROM PENALTIES pen WHERE pen.RENTAL_ID = r.RENTAL_ID), 0) AS PENALTY_AMOUNT
FROM RENTALS r
JOIN CLIENTS c ON r.CLIENT_ID = c.CLIENT_ID
JOIN CARS car ON r.CAR_ID = car.CAR_ID;
GO

CREATE OR ALTER VIEW V_MONTHLY_REVENUE AS
SELECT 
    YEAR(r.START_DATE) AS REVENUE_YEAR,
    MONTH(r.START_DATE) AS REVENUE_MONTH,
    COUNT(r.RENTAL_ID) AS TOTAL_RENTALS,
    COUNT(p.PAYMENT_ID) AS TOTAL_PAYMENTS,
    SUM(p.AMOUNT) AS TOTAL_REVENUE,
    AVG(p.AMOUNT) AS AVG_PAYMENT
FROM RENTALS r
JOIN PAYMENTS p ON r.RENTAL_ID = p.RENTAL_ID
JOIN PAYMENT_STATUSES ps ON p.STATUS_ID = ps.STATUS_ID
WHERE ps.NAME = 'PAID'
GROUP BY YEAR(r.START_DATE), MONTH(r.START_DATE);
GO

CREATE OR ALTER VIEW V_CAR_UTILIZATION AS
SELECT 
    c.CAR_ID,
    c.BRAND + ' ' + c.MODEL AS CAR_NAME,
    c.PLATE_NUMBER,
    cat.NAME AS CATEGORY_NAME,
    b.NAME AS BRANCH_NAME,
    c.STATUS AS CURRENT_STATUS,
    COUNT(r.RENTAL_ID) AS TOTAL_RENTALS,
    SUM(DATEDIFF(day, r.START_DATE, ISNULL(r.ACTUAL_RETURN_DATE, GETDATE()))) AS TOTAL_RENTAL_DAYS,
    ISNULL(SUM(r.TOTAL_PRICE), 0) AS TOTAL_REVENUE
FROM CARS c
JOIN CAR_CATEGORIES cat ON c.CATEGORY_ID = cat.CATEGORY_ID
JOIN BRANCHES b ON c.BRANCH_ID = b.BRANCH_ID
LEFT JOIN RENTALS r ON c.CAR_ID = r.CAR_ID AND r.STATUS IN ('COMPLETED', 'ACTIVE', 'EXTENDED')
GROUP BY c.CAR_ID, c.BRAND, c.MODEL, c.PLATE_NUMBER, cat.NAME, b.NAME, c.STATUS;
GO

CREATE OR ALTER VIEW V_HIGH_RISK_CLIENTS AS
SELECT 
    c.CLIENT_ID,
    c.FIRST_NAME + ' ' + c.LAST_NAME AS CLIENT_NAME,
    c.EMAIL,
    c.IS_BLOCKED,
    c.PENALTY_MULTIPLIER,
    COUNT(p.PENALTY_ID) AS PENALTY_COUNT,
    ISNULL(SUM(p.AMOUNT), 0) AS TOTAL_PENALTY_AMOUNT
FROM CLIENTS c
JOIN PENALTIES p ON c.CLIENT_ID = p.CLIENT_ID
GROUP BY c.CLIENT_ID, c.FIRST_NAME, c.LAST_NAME, c.EMAIL, c.IS_BLOCKED, c.PENALTY_MULTIPLIER
HAVING COUNT(p.PENALTY_ID) > 1 OR ISNULL(SUM(p.AMOUNT), 0) > 1000;
GO
