-- ============================================
-- CarRent DB - Role i uprawnienia
-- ============================================

-- ==========================================
-- TWORZENIE RÓL
-- ==========================================

CREATE ROLE ROLE_ADMIN;
CREATE ROLE ROLE_EMPLOYEE;
CREATE ROLE ROLE_CLIENT;
CREATE ROLE ROLE_ANALYST;

-- ==========================================
-- ROLE_ADMIN - pełny dostęp
-- ==========================================

GRANT ALL PRIVILEGES TO ROLE_ADMIN;

-- ==========================================
-- ROLE_EMPLOYEE - obsługa klientów i wypożyczeń
-- ==========================================

-- Tabele - odczyt
GRANT SELECT ON CLIENTS TO ROLE_EMPLOYEE;
GRANT SELECT ON CARS TO ROLE_EMPLOYEE;
GRANT SELECT ON RENTALS TO ROLE_EMPLOYEE;
GRANT SELECT ON RESERVATIONS TO ROLE_EMPLOYEE;
GRANT SELECT ON PAYMENTS TO ROLE_EMPLOYEE;
GRANT SELECT ON PENALTIES TO ROLE_EMPLOYEE;
GRANT SELECT ON BRANCHES TO ROLE_EMPLOYEE;
GRANT SELECT ON CAR_CATEGORIES TO ROLE_EMPLOYEE;
GRANT SELECT ON RESERVATION_STATUSES TO ROLE_EMPLOYEE;
GRANT SELECT ON PAYMENT_STATUSES TO ROLE_EMPLOYEE;
GRANT SELECT ON SERVICE_STATUSES TO ROLE_EMPLOYEE;
GRANT SELECT ON SERVICES TO ROLE_EMPLOYEE;

-- Tabele - zapis
GRANT INSERT, UPDATE ON CLIENTS TO ROLE_EMPLOYEE;
GRANT INSERT, UPDATE ON RENTALS TO ROLE_EMPLOYEE;
GRANT INSERT, UPDATE ON RESERVATIONS TO ROLE_EMPLOYEE;
GRANT INSERT, UPDATE ON PAYMENTS TO ROLE_EMPLOYEE;
GRANT INSERT ON PENALTIES TO ROLE_EMPLOYEE;
GRANT UPDATE ON CARS TO ROLE_EMPLOYEE;
GRANT INSERT, UPDATE ON SERVICES TO ROLE_EMPLOYEE;

-- Widoki
GRANT SELECT ON V_AVAILABLE_CARS TO ROLE_EMPLOYEE;
GRANT SELECT ON V_CLIENT_RENTALS TO ROLE_EMPLOYEE;
GRANT SELECT ON V_CAR_UTILIZATION TO ROLE_EMPLOYEE;

-- Pakiety
GRANT EXECUTE ON PKG_RENTAL TO ROLE_EMPLOYEE;
GRANT EXECUTE ON PKG_PAYMENT TO ROLE_EMPLOYEE;

-- ==========================================
-- ROLE_CLIENT - rezerwacja i podgląd
-- ==========================================

-- Widoki (ograniczony dostęp przez widoki)
GRANT SELECT ON V_AVAILABLE_CARS TO ROLE_CLIENT;
GRANT SELECT ON V_CLIENT_RENTALS TO ROLE_CLIENT;

-- Tabele - ograniczony odczyt
GRANT SELECT ON CAR_CATEGORIES TO ROLE_CLIENT;
GRANT SELECT ON BRANCHES TO ROLE_CLIENT;
GRANT SELECT ON RESERVATION_STATUSES TO ROLE_CLIENT;

-- Rezerwacje - klient może tworzyć
GRANT INSERT ON RESERVATIONS TO ROLE_CLIENT;

-- ==========================================
-- ROLE_ANALYST - tylko odczyt + raporty
-- ==========================================

-- Widoki
GRANT SELECT ON V_AVAILABLE_CARS TO ROLE_ANALYST;
GRANT SELECT ON V_CLIENT_RENTALS TO ROLE_ANALYST;
GRANT SELECT ON V_MONTHLY_REVENUE TO ROLE_ANALYST;
GRANT SELECT ON V_CAR_UTILIZATION TO ROLE_ANALYST;
GRANT SELECT ON V_HIGH_RISK_CLIENTS TO ROLE_ANALYST;

-- Tabele - tylko odczyt
GRANT SELECT ON CLIENTS TO ROLE_ANALYST;
GRANT SELECT ON CARS TO ROLE_ANALYST;
GRANT SELECT ON RENTALS TO ROLE_ANALYST;
GRANT SELECT ON RESERVATIONS TO ROLE_ANALYST;
GRANT SELECT ON PAYMENTS TO ROLE_ANALYST;
GRANT SELECT ON PENALTIES TO ROLE_ANALYST;
GRANT SELECT ON BRANCHES TO ROLE_ANALYST;
GRANT SELECT ON EMPLOYEES TO ROLE_ANALYST;
GRANT SELECT ON CAR_CATEGORIES TO ROLE_ANALYST;
GRANT SELECT ON SERVICES TO ROLE_ANALYST;
GRANT SELECT ON CHANGE_HISTORY TO ROLE_ANALYST;

-- Pakiet raportów
GRANT EXECUTE ON PKG_REPORTS TO ROLE_ANALYST;
