-- ============================================
-- CarRent DB - Usunięcie wszystkich obiektów
-- Wykonywać w podanej kolejności!
-- ============================================

-- Pakiety
DROP PACKAGE PKG_SECURITY;
DROP PACKAGE PKG_REPORTS;
DROP PACKAGE PKG_PAYMENT;
DROP PACKAGE PKG_RENTAL;

-- Funkcje
DROP FUNCTION get_client_penalty_count;
DROP FUNCTION calculate_penalty_multiplier;
DROP FUNCTION check_car_availability;
DROP FUNCTION calculate_rental_price;

-- Procedury
DROP PROCEDURE block_high_risk_clients;
DROP PROCEDURE archive_old_rentals;
DROP PROCEDURE generate_monthly_report;

-- Widoki
DROP VIEW V_HIGH_RISK_CLIENTS;
DROP VIEW V_CAR_UTILIZATION;
DROP VIEW V_MONTHLY_REVENUE;
DROP VIEW V_CLIENT_RENTALS;
DROP VIEW V_AVAILABLE_CARS;

-- Tabele (w kolejności zależności FK)
DROP TABLE CHANGE_HISTORY CASCADE CONSTRAINTS;
DROP TABLE SERVICES CASCADE CONSTRAINTS;
DROP TABLE PENALTIES CASCADE CONSTRAINTS;
DROP TABLE PAYMENTS CASCADE CONSTRAINTS;
DROP TABLE RENTALS CASCADE CONSTRAINTS;
DROP TABLE RESERVATIONS CASCADE CONSTRAINTS;
DROP TABLE CARS CASCADE CONSTRAINTS;
DROP TABLE CLIENTS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;
DROP TABLE BRANCHES CASCADE CONSTRAINTS;
DROP TABLE SERVICE_STATUSES CASCADE CONSTRAINTS;
DROP TABLE PAYMENT_STATUSES CASCADE CONSTRAINTS;
DROP TABLE RESERVATION_STATUSES CASCADE CONSTRAINTS;
DROP TABLE CAR_CATEGORIES CASCADE CONSTRAINTS;

-- Role
DROP ROLE ROLE_ANALYST;
DROP ROLE ROLE_CLIENT;
DROP ROLE ROLE_EMPLOYEE;
DROP ROLE ROLE_ADMIN;
